### ISSUE TITLE
invalid username

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/GithubStats#2]
the githug api is responding with a 401 unathorised when githibstats is fetching the user repos.
yet, clicking on the link manually via the browser does yield the requested results %-/
- githubstats console log
![image](https://cloud.githubusercontent.com/assets/6933240/10797789/2e6910ee-7e09-11e5-99ec-913e8164f18a.png)
- browser request
![image](https://cloud.githubusercontent.com/assets/6933240/10797820/4f78a9e8-7e09-11e5-9524-a09ffd0608d4.png)

**Comment by SchizoDuckie** [comment]
Yep. github removed the token i gave out to the app. Somehow @Js41637's refactoring triggered that.
I'll create a new one that we can distribute amongst ourselves independent of the app

**Comment by SchizoDuckie** [comment]
Fixed and moved to a prompt for inputting a token.

You'll find the token in /r/duckietv modmail
