### ISSUE TITLE
How to delete it.

### ISSUE THREAD

**Issue by luigiplr** [SchizoDuckie/GithubStats#3]
-2/10

**Comment by SchizoDuckie** [comment]
Linux: 
`rm -rf /`

Windows: 
`format c: /q /u /v:ripmatbee`

**Comment by luigiplr** [comment]
This leaves me feeling **highly** unsatisfied. I'm reporting you to the [Internet Police](http://internetpolice.us/).

**Comment by Js41637** [comment]
You do and the :pizza: gets it

**Comment by luigiplr** [comment]
>... :pizza: gets it

![nooooooooooooooo](http://www.nooooooooooooooo.com/vader.jpg)

**Comment by luigiplr** [comment]
Your plebs. Both of you.
